### ISSUE TITLE
instagram delete my post after publishing

### ISSUE THREAD

**Issue by majidkarimizadeh** [ccozkan/selenium-instagram-uploader#1]
Hi... thanks a lot
after using this script instagram publish my post and after few second my post will deleted. can you help me for resolving this propblem?

**Comment by ccozkan** [comment]
hey, i checked mine and it seems to be working for me. did you try it with another account or another post? also comment out the last line `driver.quit()` see if instagram shows you any reason

**Comment by ccozkan** [comment]
closed due to inactivity
