### ISSUE TITLE
Wrong Code

### ISSUE THREAD

**Issue by Lucifer1590** [ccozkan/selenium-instagram-uploader#5]
This thing Literally got my head scratched 

you have said to save the script as image_select 
![Capture](https://user-images.githubusercontent.com/72858502/97867105-35ea0980-1d33-11eb-835a-7c578c3cd1b0.PNG)

but in main script you have given the command select_image
![Capture1](https://user-images.githubusercontent.com/72858502/97867162-51edab00-1d33-11eb-8b82-4d42b89841a4.PNG)

it was impossible to get desired results from that code and i had spent hours tracking where was mistake 😞 . It turns out this was 

So Please update the code

**Comment by ccozkan** [comment]
sorry about that:/ fixed the typo years ago but forgot to close it, thanks for pointing out though
